#ifndef CONFIG_H
#define CONFIG_H

#define BACKLOG_QUEUE_LEN 10
#define NO_FLAGS 0
#define READ_BUFFER_SIZE 10000
#define RESOURCE_URL_SIZE 50
#define MAX_RESPONSE_SIZE 1000
#define NUM_OF_THREADS 5
#define CONTENT_TYPE_SIZE 40

#endif